apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-eks-example-hugepages
  region: us-west-2

nodeGroups:
  - name: ng-1
    labels:  
      worker: default
    instanceType: m5.xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true
    preBootstrapCommands:
    - sudo sysctl -w vm.nr_hugepages=2048

availabilityZones: ['us-west-2a', 'us-west-2b', 'us-west-2c']
