apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: iris-demo-basic
spec:
  passwordHash: 4612128bf59d68492310e1c94b90860e4d26fd93,rq2tkvjg
  licenseKeySecret:
    name: iris-key-secret
  configSource:
    name: iris-cpf
  topology:
    arbiter:
      image: intersystems/arbiter:2020.1.0-stable
      preferredZones:
        - us-west-2d
      podTemplate:
        spec:
          imagePullSecrets:
            - name: dockerhub-secret
    data:
      shards: 1
      mirrored: false
      image: intersystems/iris:2020.1.0-stable
      preferredZones:
        - us-west-2b 
        - us-west-2c
      podTemplate:
        spec:
          serviceAccountName: bobtest-account
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          imagePullSecrets:
            - name: dockerhub-secret
      updateStrategy:
        type: RollingUpdate
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: iris-ssd-storageclass
    compute:
      image: intersystems/iris:2020.1.0-stable
      replicas: 0
      preferredZones:
        - us-west-2b
        - us-west-2c
      podTemplate:
        spec:
          imagePullSecrets:
            - name: dockerhub-secret
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: iris-ssd-storageclass
  serviceTemplate:
    spec:
      type: LoadBalancer
