apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: iris-demo-basic
spec:
  passwordHash: 4612128bf59d68492310e1c94b90860e4d26fd93,rq2tkvjg
  licenseKeySecret:
    name: iris-key-secret
  configSource:
    name: iris-cpf
  topology:
    arbiter:
      image: containers.intersystems.com/intersystems/arbiter:2020.4.0.524.0
      podTemplate:
        spec:
          imagePullSecrets:
            - name: intersystems-container-registry-secret
    data:
      shards: 1
      mirrored: false
      image: containers.intersystems.com/intersystems/iris:2020.4.0.524.0
      podTemplate:
        spec:
          imagePullSecrets:
            - name: intersystems-container-registry-secret
      updateStrategy:
        type: RollingUpdate
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: iris-ssd-storageclass
    compute:
      image: containers.intersystems.com/intersystems/iris:2020.4.0.524.0
      replicas: 0
      podTemplate:
        spec:
          imagePullSecrets:
            - name: intersystems-container-registry-secret
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: iris-ssd-storageclass
  serviceTemplate:
    spec:
      type: clusterIP
