apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: sample
spec:
  licenseKeySecret:
    name: iris-key-secret
  configSource:
    name: iris-cpf

  storageClassName: iris-ssd-storageclass
   
## create external IP address(es)for the cluster 
## ("type: LoadBalancer" and "externalTrafficPolicy: Local" are required)
  serviceTemplate:
    spec:
      type: NodePort
      ports:
      - name: MgmtPortal
        nodePort: 30080
        port: 52773
#      type: LoadBalancer 
#      externalTrafficPolicy: Local

## topology: defines node types to be deployed; only data: is required

  topology:
    data:
      image: containers.intersystems.com/intersystems/iris:2022.1.0.140.0
      shards: 1
      mirrored: false
## override default size and other attributes of predefined storage 
## volumes for data nodes (additional volume names: storageWIJ, 
## storageJournal1, storageJournal2); can also be included in 
## "compute:" definition
#      storageDB:
#        resources:
#          requests:
#            storage: 10Gi
#        storageClassName: my-storage-class
