apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-mirror-labeler
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iris-mirror-labeler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iris-mirror-labeler
    spec:
      serviceAccountName: iris-mirror-labeler
      containers:
      - image: <YOUR IMAGE HERE>
        name: mirror-labeler
      restartPolicy: Always
      schedulerName: default-scheduler
